### ISSUE TITLE
Can't access to Models directly from the module.

### ISSUE THREAD

**Issue by Raven0uss** [Image4IO/image4ionodeSDK#3]
Hello,

You have only the v0.1.0 available on npm, the v1.0.0 and v.1.0.1 (most recent) is not because only the README and your `package.json` is present in the registery, i let you check (and it's because you have `src` in the `.npmignore`. So if i want to use your product I have to download your repo (thing I don't want) or use a deprecated version without documentation (I don't want too :cry:  ). But, hopefully I want to use your product :tada: 

One more thing : 
```
var getRes = api.GetImage(new Models.GetImageRequest("/folderName/test.png"));
getRes.then(response => {
    //Response returns a JSON object, which can be accessed here
}).catch(error => {
    throw error;
})
```
Ok, but the problem is, if I use it like above in my application, I can't see why I should import also the constructor `Models.GetImageRequest` (and it's apparently not possible, you only export `Image4ioAPI`), just use it in the method to simplify the call like that : `api.GetImage("/folderName/test.png")` 

Thanks.

**Comment by gkocyigit** [comment]
Issue is resolved in v1.0.3. It is available on npm.
Thanks for reporting!
